### ISSUE TITLE
 Remove admin-mode requirement

### ISSUE THREAD

**Issue by Sobuno** [Sobuno/SWGAide#1]
Currently, SWGAide has a note about requiring admin mode. It is, however, unclear why admin mode is actually requested.

Find out what elements of SWGAide requires admin mode and see if they can be changed, so that admin-mode is completely optional.

**Comment by cbortz** [comment]
Have you seen this?

> "The problem is not where SWGAide is located, if you look in the general log file there are probably dozens of messages about mails and stuff, right.
> 
> I use both XP and Windows 7 now but on the latter I had to do exactly what is read in the README file that comes in the ZIP file you downloaded. It boils down to that Microsoft treats Java with an upper hand and disallows Java applications normal freedom while they work; you need to manually allow a file in the Java installation to execute in admin mode.
> 
> If there is some other kind of issue for this I'd be happy to help, if so you must probably send me the two log filesby email.
> 
> Zimoon"
> 
> _Source: [Thread "Help With SWGAide please" @ SWGCraft.org](http://www.swgcraft.org/forums/viewtopic.php?f=43&t=1304&start=15#p16877)_

**Comment by Sobuno** [comment]
Have you encountered an issue with running without admin mode? Looking in the thread, it seems they have issue with having SWG in the Program Files folder. I tried browsing both the "Program Files" and "Program Files (x86)" folders in the initialization phase, but I seemed to be able to access them just fine in SWGAide's "Select SWG folder" dialog.

I haven't tried setting up my (dummy) SWG folder in there though and seeing if it actually works to have it assigned that way.

**Comment by cbortz** [comment]
Personally, I was able to select the SWG folder without problem. However, SWGAide wouldn't actually read any data until I ran it in admin mode.

I think what Zimoon was trying to say is that it's a problem with how Windows treats Java applications. I wonder if there's a way to circumvent this, or at the very least, ask the user for permission?

Note: Windows is not my primary OS. I use it for gaming and some testing but that's about it.

**Comment by Sobuno** [comment]
Ah, okay, so it's an issue if SWG is located in certain folders, got it.

Admin mode is the primary reason that I create the .exe version for every release. launch4j, the utility I use to create it, has a setting that allows me to have the application automatically ask for admin mode + it allows me to give the application a shiny icon!
